version: '3.9'

services:
  yplaravelboilerplate_app:
    build: .
    container_name: yplaravelboilerplate_app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - yplaravelboilerplate_network
    depends_on:
      - yplaravelboilerplate_db
    command: sh -c "until nc -z yplaravelboilerplate_db 5432; do sleep 1; done; php artisan migrate && php-fpm"

  yplaravelboilerplate_webserver:
    image: nginx:alpine
    container_name: yplaravelboilerplate_webserver
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - yplaravelboilerplate_network
    depends_on:
      - yplaravelboilerplate_app

  yplaravelboilerplate_db:
    image: postgres:15
    container_name: yplaravelboilerplate_db
    environment:
      POSTGRES_DB: yplaravelboilerplate_db
      POSTGRES_USER: yplaravelboilerplate_db
      POSTGRES_PASSWORD: yplaravelboilerplate_db
    ports:
      - "5432:5432"
    volumes:
      - yplaravelboilerplate_db_data:/var/lib/postgresql/data
    networks:
      - yplaravelboilerplate_network

volumes:
  yplaravelboilerplate_db_data:

networks:
  yplaravelboilerplate_network:
    driver: bridge
